version: '3.7'
services:
    postgres:
        container_name: orange-database-postgres
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        restart: always
        volumes:
            - orange_postgres_volume:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - orange
volumes:
    orange_postgres_volume:
networks:
    orange:
        driver: bridge
